### PR TITLE
RFC: client didn't check response_headers

### PR DESCRIPTION
**Pull request by jameysharp**
The client was checking `header.len`, but that always evaluates to `undefined`; it should have been `header.length`. This meant that, contrary to the documentation, the client didn't actually check that the headers it told the server to send actually made it through the proxy.

Fixing that is easy, but then there are a bunch of spurious test failures. One reason is that the proxy is allowed to change the headers in certain ways, such as merging multiple `Cache-Control` headers into a single header. Even if multiple headers are returned, the simplistic loop here doesn't correctly check that the multiple headers the server sent are the same as the multiple headers the client received. And even for single headers, there's a lot of code in the server to rewrite headers like dates or `Surrogate-Control`, which would need to be mirrored in the client.

So I'm not sure: is it worth-while to have the client try to check the returned headers at all? Or should we just delete the currently-dead code and make the documentation match the existing behavior?

In this draft PR I've re-run the Squid tests so you can see an example of the kinds of failures this produces, and also annotated some multiple-header tests to skip checking those headers.

I do think one failure this catches is interesting: the new setup-phase error for `conditional-etag-strong-respond-obs-text` through Squid looks like an encoding disagreement (`Response 1 header ETag is \"\"abcdefÃ¼\"\", not \"\"abcdefü\"\""`) so I'm not sure if that's a meaningful test result in a conditional test. Perhaps it should depend on a different test verifying that `obs-text` is passed through the proxy as opaque bytes?

### CODE REVIEW

**Comment by mnot** [comment]
Damn my Python brain. :-/

That sounds about right; I'll take a look in a few days (am currently on the road).

Thanks!

**Comment by jameysharp** [comment]
I'm rarely a JavaScript programmer myself; I only noticed this because I tried to copy-paste that expression for my other PR and it didn't work. :sweat_smile:

No rush on this. Thanks for taking a look!

**Comment by mnot** [comment]
So, some of the remaining failures are because the modifications starting at server.js#154 need to be copied over; you've done dates but not location or surrogate-control. In an ideal world this code wouldn't be copied, but the weirdness around JS modules in browsers vs. node mean that it probably will be, at least for the time being. Perhaps that code could be factored out a bit more so that at least the copies would be identical (or almost so).

A few more failures are because the setup is wrongly checking for hop-by-hop headers to exist (e.g., `Connection`, `Proxy-Authenticate`, `Transfer-Encoding`, `Upgrade` and the like). I think the tests themselves should be corrected (by adding `false` to `expected_headers` as required).

The `Set-Cookie` failures look legitimate; it seems like it's just catching the fact that Squid is stripping the header earlier.

Tell me if you want help with this, and thanks again.

**Comment by jameysharp** [comment]
I think this new series of commits pretty well takes care of all these issues.

I took a somewhat simpler approach than copying code from server to client. Instead I have the server record, into the test state, the headers that it generated, so the client can do simple comparisons against that at the end of the test. This is basically the mirror-image of checking request headers.

I was careful about commit ordering in two ways: If an old client is used with a new server, or vice versa, these changes shouldn't trigger any spurious test failures; and if `git bisect` lands on any of the intermediate commits then it shouldn't fail any tests that didn't fail before. I'm a little irritated that the GitHub UI is sorting the commits by author date though, so you can't tell what order I rebased them into.

One weird case in the results is `304-lm-use-stored-Test-Header` on nginx. With this change, that test reports `Response 2 header Cache-Control is "max-age=1", not "max-age=3600"`. I think the error message is correct: nginx should have updated the `Cache-Control` header from the 304. But I'm not sure: should that be treated as a setup error for this particular test, or should it be ignored in this case?

Because I've updated the test results in both this PR and my other one, they'll merge-conflict. But if you drop the last ("update results") commit from one or both branches, there are no merge conflicts and git's auto-merge bits do the right thing.

**Pull request merged**
